# Generated by Django 5.2.15 on 2026-06-06 09:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=250)),
                ('normalized_term', models.CharField(blank=True, max_length=250)),
                ('part_of_speech', models.CharField(blank=True, max_length=80)),
                ('ipa', models.CharField(blank=True, max_length=160)),
                ('short_definition', models.CharField(max_length=500)),
                ('definition', models.TextField()),
                ('examples', models.JSONField(blank=True, default=list)),
                ('forms', models.JSONField(blank=True, default=dict)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
                ('collocations', models.JSONField(blank=True, default=list)),
                ('usage_notes', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='CardSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning'), ('suspended', 'Suspended')], default='new', max_length=16)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_days', models.FloatField(default=0.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('step_index', models.PositiveSmallIntegerField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='learning.flashcard')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('accent', models.CharField(default='violet', max_length=24)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LlmUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('generation', 'Generation'), ('bulk_generation', 'Bulk generation'), ('judging', 'Judging')], max_length=32)),
                ('model', models.CharField(max_length=250)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('elapsed_time', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to='learning.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to='learning.pool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='learning.pool'),
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('term_to_definition', 'Word → definition'), ('definition_to_term', 'Definition → word')], max_length=32)),
                ('answer', models.TextField(blank=True)),
                ('judge_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('judge_verdict', models.CharField(blank=True, max_length=40)),
                ('feedback', models.TextField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('previous_state', models.CharField(max_length=16)),
                ('new_state', models.CharField(max_length=16)),
                ('previous_interval_days', models.FloatField(default=0.0)),
                ('new_interval_days', models.FloatField(default=0.0)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='learning.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=16)),
                ('study_direction', models.CharField(choices=[('mixed', 'Mixed'), ('term_to_definition', 'Word → definition'), ('definition_to_term', 'Definition → word')], default='mixed', max_length=32)),
                ('generation_model', models.CharField(default='external:deepseek-chat', max_length=200)),
                ('generation_token_encrypted', models.TextField(blank=True)),
                ('judge_model', models.CharField(default='external:deepseek-chat', max_length=200)),
                ('judge_token_encrypted', models.TextField(blank=True)),
                ('judge_acceptance_score', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('reveal_threshold', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('daily_new_limit', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('learning_steps_minutes', models.JSONField(default=learning.models.default_learning_steps)),
                ('relearning_steps_minutes', models.JSONField(default=learning.models.default_relearning_steps)),
                ('graduating_interval_days', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('easy_interval_days', models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('easy_bonus', models.FloatField(default=1.3, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('hard_multiplier', models.FloatField(default=1.2, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('lapse_multiplier', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('minimum_ease', models.FloatField(default=1.3, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_pool_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.UniqueConstraint(fields=('pool', 'normalized_term'), name='unique_term_per_pool'),
        ),
    ]
