# Generated by Django 5.2.16 on 2026-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_per_provider_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='image_thumb',
            field=models.FileField(blank=True, default='', upload_to='cards/thumbs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_card_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='llmusage',
            name='operation',
            field=models.CharField(choices=[('generation', 'Generation'), ('bulk_generation', 'Bulk generation'), ('judging', 'Judging'), ('image', 'Image lookup')], max_length=32),
        ),
    ]
