# Generated by Django 5.2.16 on 2026-07-11 14:24

import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_flashcard_image_flashcard_image_thumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_animations',
            field=models.JSONField(blank=True, default=learning.models.default_image_animations),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_images_definition_to_term',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_images_term_to_definition',
            field=models.BooleanField(default=True),
        ),
    ]
