# Generated by Django 5.2.16 on 2026-07-11 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_userprofile_image_animations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_animation_durations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_prefetch_count',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
