# Generated by Django 5.2.16 on 2026-07-11 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_droplets_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sentence_acceptance_score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sentence_judge_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sentence_reveal_threshold',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_images_term_to_sentence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='term_to_sentence_easy_seconds',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='term_to_sentence_good_seconds',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AlterField(
            model_name='llmusage',
            name='operation',
            field=models.CharField(choices=[('generation', 'Generation'), ('bulk_generation', 'Bulk generation'), ('judging', 'Judging'), ('sentence_judging', 'Sentence judging'), ('image', 'Image lookup')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='direction',
            field=models.CharField(choices=[('term_to_definition', 'Word → definition'), ('definition_to_term', 'Definition → word'), ('term_to_sentence', 'Word → sentence')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='study_direction',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('term_to_definition', 'Word → definition'), ('definition_to_term', 'Definition → word'), ('term_to_sentence', 'Word → sentence')], default='mixed', max_length=32),
        ),
    ]
