# Generated by Django 5.2.16 on 2026-07-11 20:05

import learning.models
from django.db import migrations, models

# The single-select study_direction becomes the study_directions list; the
# obsolete auto-reveal thresholds are dropped (revealing stopped being a
# separate step when the study flow was collapsed into check → result → next).
DIRECTION_TO_LIST = {
    'mixed': ['term_to_definition', 'definition_to_term'],  # sentence stays opt-in
    'term_to_definition': ['term_to_definition'],
    'definition_to_term': ['definition_to_term'],
    'term_to_sentence': ['term_to_sentence'],
}


def forwards(apps, schema_editor):
    UserProfile = apps.get_model('learning', 'UserProfile')
    for profile in UserProfile.objects.all().iterator():
        profile.study_directions = DIRECTION_TO_LIST.get(
            profile.study_direction, ['term_to_definition', 'definition_to_term'])
        profile.save(update_fields=['study_directions'])


def backwards(apps, schema_editor):
    UserProfile = apps.get_model('learning', 'UserProfile')
    for profile in UserProfile.objects.all().iterator():
        enabled = profile.study_directions or []
        profile.study_direction = enabled[0] if len(enabled) == 1 else 'mixed'
        profile.save(update_fields=['study_direction'])


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_userprofile_sentence_acceptance_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reveal_threshold',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sentence_reveal_threshold',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='study_directions',
            field=models.JSONField(default=learning.models.default_study_directions),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='userprofile',
            name='study_direction',
        ),
    ]
