# Generated by Django 5.2.15 on 2026-08-14 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_provider_catalog_overrides_and_deepseek_v4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_card_order',
            field=models.CharField(choices=[('mixed', 'Mix with reviews'), ('after_reviews', 'Show after reviews'), ('before_reviews', 'Show before reviews')], default='mixed', max_length=16),
        ),
        migrations.CreateModel(
            name='RouterAdapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('source_code', models.TextField()),
                ('author_model', models.CharField(blank=True, max_length=250)),
                ('screening', models.JSONField(blank=True, default=dict)),
                ('canary', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router_adapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', '-revision'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'revision'), name='unique_adapter_revision_per_provider'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('provider',), name='one_active_adapter_per_provider')],
            },
        ),
    ]
