#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="${LEXILOOP_APP_DIR:-/opt/lexiloop}"
APP_USER="${LEXILOOP_USER:-lexiloop}"
APP_GROUP="${LEXILOOP_GROUP:-lexiloop}"
SERVICE="${LEXILOOP_SERVICE:-lexiloop}"
BULK_SERVICE="${LEXILOOP_BULK_SERVICE:-lexiloop-bulk}"
TARGET_DATABASE_URL="${TARGET_DATABASE_URL:-${1:-}}"

if [[ ${EUID} -ne 0 ]]; then
  echo "Error: run as root (sudo)." >&2
  exit 1
fi
if [[ -z "$TARGET_DATABASE_URL" || "$TARGET_DATABASE_URL" != postgres* ]]; then
  echo "Usage: sudo env TARGET_DATABASE_URL='postgresql://user:password@127.0.0.1:5432/lexiloop' $0" >&2
  exit 1
fi
for command in systemctl pg_dump pg_restore psql; do
  command -v "$command" >/dev/null 2>&1 || { echo "Error: missing command: $command" >&2; exit 1; }
done
[[ -x "$APP_DIR/.venv/bin/python" ]] || { echo "Error: LexiLoop virtualenv not found." >&2; exit 1; }
[[ -f "$APP_DIR/.env" ]] || { echo "Error: $APP_DIR/.env not found." >&2; exit 1; }

CURRENT_ENGINE="$($APP_DIR/.venv/bin/python - <<PY
import os, sys
sys.path.insert(0, '$APP_DIR/backend')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
import django
django.setup()
from django.conf import settings
print(settings.DATABASES['default']['ENGINE'])
PY
)"
if [[ "$CURRENT_ENGINE" != "django.db.backends.sqlite3" ]]; then
  echo "Error: the active database is not SQLite ($CURRENT_ENGINE). Nothing was changed." >&2
  exit 1
fi

SQLITE_NAME="$($APP_DIR/.venv/bin/python - <<PY
import os, sys
sys.path.insert(0, '$APP_DIR/backend')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
import django
django.setup()
from django.conf import settings
print(settings.DATABASES['default']['NAME'])
PY
)"
[[ -f "$SQLITE_NAME" ]] || { echo "Error: SQLite file not found: $SQLITE_NAME" >&2; exit 1; }

STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="/var/backups/lexiloop/postgres-migration/$STAMP"
install -d -m 700 -o "$APP_USER" -g "$APP_GROUP" "$BACKUP_DIR"
SERVICE_WAS_ACTIVE=0; BULK_WAS_ACTIVE=0
systemctl is-active --quiet "$SERVICE" && SERVICE_WAS_ACTIVE=1 || true
systemctl is-active --quiet "$BULK_SERVICE" && BULK_WAS_ACTIVE=1 || true

restart_old() {
  local status=$?
  trap - ERR INT TERM
  echo "Migration failed. SQLite remains active; backup: $BACKUP_DIR" >&2
  cp -a "$BACKUP_DIR/.env" "$APP_DIR/.env" 2>/dev/null || true
  if (( SERVICE_WAS_ACTIVE )); then systemctl start "$SERVICE" || true; fi
  if (( BULK_WAS_ACTIVE )); then systemctl start "$BULK_SERVICE" || true; fi
  exit "$status"
}
trap restart_old ERR INT TERM

systemctl stop "$BULK_SERVICE" 2>/dev/null || true
systemctl stop "$SERVICE" 2>/dev/null || true
cp -a "$APP_DIR/.env" "$BACKUP_DIR/.env"
cp -a "$SQLITE_NAME" "$BACKUP_DIR/db.sqlite3"

SOURCE_DATABASE_URL="sqlite:///$SQLITE_NAME"
cd "$APP_DIR/backend"

# Serialize application data while SQLite is quiescent. Content types and
# permissions are regenerated by migrate on the target database.
if command -v sudo >/dev/null 2>&1; then RUN_AS=(sudo -u "$APP_USER" -H env); else RUN_AS=(runuser -u "$APP_USER" -- env); fi
"${RUN_AS[@]}" DATABASE_URL="$SOURCE_DATABASE_URL" ../.venv/bin/python manage.py dumpdata \
  --exclude contenttypes \
  --exclude auth.permission \
  --exclude admin.logentry \
  --exclude sessions.session \
  --natural-foreign \
  --indent 2 \
  --output "$BACKUP_DIR/lexiloop-data.json"

SOURCE_COUNTS="$("${RUN_AS[@]}" DATABASE_URL="$SOURCE_DATABASE_URL" ../.venv/bin/python manage.py shell --no-imports -c \
  "from django.contrib.auth.models import User; from learning.models import Pool,Flashcard,ReviewLog,LlmUsage,BulkGenerationJob; print(User.objects.count(),Pool.objects.count(),Flashcard.objects.count(),ReviewLog.objects.count(),LlmUsage.objects.count(),BulkGenerationJob.objects.count())")"
printf '%s\n' "$SOURCE_COUNTS" > "$BACKUP_DIR/source-counts.txt"

"${RUN_AS[@]}" DATABASE_URL="$TARGET_DATABASE_URL" ../.venv/bin/python manage.py migrate --noinput
TARGET_USERS="$("${RUN_AS[@]}" DATABASE_URL="$TARGET_DATABASE_URL" ../.venv/bin/python manage.py shell --no-imports -c "from django.contrib.auth.models import User; print(User.objects.count())")"
if [[ "$TARGET_USERS" != "0" ]]; then
  echo "Error: target PostgreSQL database already contains users. Use an empty database." >&2
  false
fi
"${RUN_AS[@]}" DATABASE_URL="$TARGET_DATABASE_URL" ../.venv/bin/python manage.py loaddata "$BACKUP_DIR/lexiloop-data.json"
"${RUN_AS[@]}" DATABASE_URL="$TARGET_DATABASE_URL" ../.venv/bin/python manage.py sqlsequencereset auth authtoken learning \
  | "${RUN_AS[@]}" DATABASE_URL="$TARGET_DATABASE_URL" ../.venv/bin/python manage.py dbshell

TARGET_COUNTS="$("${RUN_AS[@]}" DATABASE_URL="$TARGET_DATABASE_URL" ../.venv/bin/python manage.py shell --no-imports -c \
  "from django.contrib.auth.models import User; from learning.models import Pool,Flashcard,ReviewLog,LlmUsage,BulkGenerationJob; print(User.objects.count(),Pool.objects.count(),Flashcard.objects.count(),ReviewLog.objects.count(),LlmUsage.objects.count(),BulkGenerationJob.objects.count())")"
printf '%s\n' "$TARGET_COUNTS" > "$BACKUP_DIR/target-counts.txt"
if [[ "$SOURCE_COUNTS" != "$TARGET_COUNTS" ]]; then
  echo "Error: source and target record counts differ." >&2
  echo "SQLite:    $SOURCE_COUNTS" >&2
  echo "PostgreSQL: $TARGET_COUNTS" >&2
  false
fi

TARGET_DATABASE_URL="$TARGET_DATABASE_URL" ENV_PATH="$APP_DIR/.env" "$APP_DIR/.venv/bin/python" - <<'PY'
import json, os
from pathlib import Path
path = Path(os.environ['ENV_PATH'])
value = os.environ['TARGET_DATABASE_URL']
lines = path.read_text(encoding='utf-8').splitlines()
replacement = f"DATABASE_URL={json.dumps(value)}"
out=[]; replaced=False
for line in lines:
    if line.startswith('DATABASE_URL='):
        if not replaced:
            out.append(replacement); replaced=True
    else:
        out.append(line)
if not replaced:
    out.append(replacement)
path.write_text('\n'.join(out)+'\n', encoding='utf-8')
PY
chown "$APP_USER:$APP_GROUP" "$APP_DIR/.env"
chmod 600 "$APP_DIR/.env"

systemctl start "$SERVICE"
systemctl start "$BULK_SERVICE"
sleep 2
systemctl is-active --quiet "$SERVICE"
systemctl is-active --quiet "$BULK_SERVICE"

trap - ERR INT TERM
echo "PostgreSQL migration completed."
echo "Record counts: $TARGET_COUNTS"
echo "SQLite safety backup: $BACKUP_DIR/db.sqlite3"
echo "Fixture and metadata: $BACKUP_DIR"
